name: Step 1

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".devcontainer/devcontainer.json"
      - ".vscode/extensions.json"

permissions:
  contents: read
  actions: write
  issues: write

env:
  STEP_2_FILE: ".github/steps/2-step.md"

jobs:
  find_exercise:
    if: ${{ github.event_name != 'push' || github.event.created == false }}
    name: Find Exercise Issue
    uses: skills/exercise-toolkit/.github/workflows/find-exercise-issue.yml@v0.8.1

  check_step_work:
    name: Check step work
    runs-on: ubuntu-latest
    needs: [find_exercise]
    env:
      ISSUE_REPOSITORY: ${{ github.repository }}
      ISSUE_NUMBER: ${{ needs.find_exercise.outputs['issue-number'] }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Get response templates
        uses: actions/checkout@v6
        with:
          repository: skills/exercise-toolkit
          path: exercise-toolkit
          ref: v0.8.1

      - name: Find last comment
        id: find-last-comment
        uses: peter-evans/find-comment@v4
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          direction: last

      - name: Update comment - checking work
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          comment-id: ${{ steps.find-last-comment.outputs.comment-id }}
          file: exercise-toolkit/markdown-templates/step-feedback/checking-work.md
          edit-mode: replace

      # START: Check practical exercise

      - name: Check if .vscode/extensions.json exists
        id: check-extensions-file
        continue-on-error: true
        uses: skills/exercise-toolkit/actions/file-exists@v0.8.1
        with:
          file: .vscode/extensions.json

      - name: Check if .devcontainer/devcontainer.json exists
        id: check-devcontainer-file
        continue-on-error: true
        uses: skills/exercise-toolkit/actions/file-exists@v0.8.1
        with:
          file: .devcontainer/devcontainer.json

      - name: Check C# Dev Kit recommendation keyphrase
        id: check-csdevkit-recommendation
        continue-on-error: true
        uses: skills/action-keyphrase-checker@v1
        with:
          text-file: .vscode/extensions.json
          keyphrase: ms-dotnettools.csdevkit

      - name: Check C# extension recommendation keyphrase
        id: check-csharp-recommendation
        continue-on-error: true
        uses: skills/action-keyphrase-checker@v1
        with:
          text-file: .vscode/extensions.json
          keyphrase: ms-dotnettools.csharp

      - name: Check C# Dev Kit devcontainer keyphrase
        id: check-csdevkit-devcontainer
        continue-on-error: true
        uses: skills/action-keyphrase-checker@v1
        with:
          text-file: .devcontainer/devcontainer.json
          keyphrase: ms-dotnettools.csdevkit

      - name: Update comment - step results
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          comment-id: ${{ steps.find-last-comment.outputs.comment-id }}
          edit-mode: replace
          file: exercise-toolkit/markdown-templates/step-feedback/step-results-table.md
          vars: |
            step_number: 1
            results_table:
              - description: "Checked if .vscode/extensions.json exists"
                passed: ${{ steps.check-extensions-file.outcome == 'success' }}
              - description: "Checked if .devcontainer/devcontainer.json exists"
                passed: ${{ steps.check-devcontainer-file.outcome == 'success' }}
              - description: "Checked C# Dev Kit recommendation keyphrase"
                passed: ${{ steps.check-csdevkit-recommendation.outcome == 'success' }}
              - description: "Checked C# extension recommendation keyphrase"
                passed: ${{ steps.check-csharp-recommendation.outcome == 'success' }}
              - description: "Checked C# Dev Kit devcontainer keyphrase"
                passed: ${{ steps.check-csdevkit-devcontainer.outcome == 'success' }}

      # END: Check practical exercise

      - name: Fail job if not all checks passed
        if: contains(steps.*.outcome, 'failure')
        run: exit 1

  post_next_step_content:
    name: Post next step content
    needs: [find_exercise, check_step_work]
    runs-on: ubuntu-latest
    env:
      ISSUE_REPOSITORY: ${{ github.repository }}
      ISSUE_NUMBER: ${{ needs.find_exercise.outputs['issue-number'] }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Get response templates
        uses: actions/checkout@v6
        with:
          repository: skills/exercise-toolkit
          path: exercise-toolkit
          ref: v0.8.1

      - name: Create comment - step finished
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: exercise-toolkit/markdown-templates/step-feedback/step-finished-prepare-next-step.md
          vars: |
            next_step_number: 2

      - name: Create comment - add step content
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: ${{ env.STEP_2_FILE }}

      - name: Create comment - watching for progress
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: exercise-toolkit/markdown-templates/step-feedback/watching-for-progress.md

      - name: Disable current workflow and enable next one
        run: |
          gh workflow disable "${{github.workflow}}"
          gh workflow enable "2-step.yml"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
